version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: my-family-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myfamily
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]

  adminer:
    image: adminer
    container_name: my-family-adminer
    restart: unless-stopped
    ports:
      - "8000:8000"

volumes:
  pgdata:
